api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    oauth:
        enabled: true
        clientId: '%env(string:OAUTH2_CLIENT_ID)%'
        clientSecret: '%env(string:OAUTH2_CLIENT_SECRET)%'
        tokenUrl: '/oauth/v2/token'
        authorizationUrl: '/oauth/v2/authorize'

doctrine:
    orm:
        filters:
            owned_entity:
                class: App\Filter\User\OwnedEntityFilter