security:
    enable_authenticator_manager: false
    password_hashers:
        App\Entity\Authentication\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Authentication\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern: ^/oauth/v2/token$
            security: false

        documentation:
            pattern: ^/$
            security: false

        main:
            security: true
            stateless: true
            oauth2: true

    access_control:
        - { path: ^/oauth/v2/authorize, roles: IS_AUTHENTICATED_REMEMBERED }